name: Build nuget-native-cli

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.101
      - name: Build nuget-native-cli
        run: make all
      - run: ls -lhR bin
      - uses: actions/upload-artifact@v2
        with:
          name: nuget-native-cli
          path: bin/**